#+TITLE: Automation Testing Selenium with Java basics
#+AUTHOR: Ravikiran
#+DATE: [2023-02-16 Thur]


* What is Automation testing ?
Automated testing tools are capable of executing tests, reporting outcomes and comparing results with earlier test runs. Tests carried out with these tools can be run repeatedly, at any time of day. The method or process being used to implement automation is called a test automation framework.

* What is Selenium ?
Selenium is an automation tool used to test the functionalities of web applications.

* What is Java ?
Java is a Programming Language. It is used to write the automation scripts using selenium.

* What is Class and Objects?
** Class
Class is a blueprint or template or form to create objects.
*** Syntax
class <Class Name>{
}
*** Example
class basics{
}

** Object
Object is the data.
*** Syntax
<class Name> <object name> = new <class Name>();
*** Example
basics bs = new basics();

|------------+----------+------------|
| Class      | Object 1 | Object 2   |
|------------+----------+------------|
| Name       | Rama     | Sita       |
| Profession | QA       | HR Manager |
| Department | IT       | HR         |
|------------+----------+------------|

* Data Types in Java
** Primitive data types
  byte, short, int, long, float, double, boolean and char

|-----------+--------+----------------------------------------------------------------|
| Data Type | Size   | Description                                                    |
|-----------+--------+----------------------------------------------------------------|
| byte      | 8-bit  | Stores whole numbers from -128 to 127                          |
|-----------+--------+----------------------------------------------------------------|
| short     | 16-bit | Stores whole numbers from -32,768 to 32,767                    |
|-----------+--------+----------------------------------------------------------------|
| int       | 32-bit | Stores whole numbers from -2^31 to 2^31                        |
|-----------+--------+----------------------------------------------------------------|
| long      | 64-bit | Stores whole numbers from -2^63 to 2^63                        |
|-----------+--------+----------------------------------------------------------------|
| float     | 32-bit | Stores fractions. Sufficient for storing 6 to 7 decimal digits |
|-----------+--------+----------------------------------------------------------------|
| double    | 64-bit | Stores fractions. Sufficient for storing 15-16 decimal digits  |
|-----------+--------+----------------------------------------------------------------|
| boolean   | 1 bit  | Stores true or false values                                    |
|-----------+--------+----------------------------------------------------------------|
| char      | 16-bit | Sotes a single character/letter or ASCII values                |
|-----------+--------+----------------------------------------------------------------|

*** Examples
byte bt = 127;
short sh = 32767;
int myInt=764765;
long lng = 765737L;

float myfloat =1.455667f;
double mydouble =1.455656d;
	
boolean bool = true/ false;
char ch = 'c';


** Non Primitive data types
String, Arrays

*** Example
There are two ways we can define the string

**** Method 1
String str1 = new String("abc");

**** Method 2
String str1 = "abc";

For more information on the data types follow the below link
[[https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/package-summary.html][Data types]]


* String
String Literal vs Object

               String str1 = "abc";  
               String str2 = new String("abc");
	       String str3 = "abc"
	       System.out.println(str1 == str2);// this will return false
	       System.out.println(str1 == str3);// this will return true
               System.out.println(str1.equals(str2)); // this will return true

In java there is a heap memory when we create str1 = "abc" it will allocate memory in it.
When we create str3 ="abc" it will check for the value in heap memory and assign to it.
But when we create the  String str2 = new String("abc")as the object is created it will create new allocation for it.
As str1 and str3 are pointing to the same memory it will give output as true.
Where as str2 is created by object when we use str1==str2 or str2==str3 it will return false.
By using ".equals" it will return true as it will compare the values.


* Variables

Variable is a container which holds the value that is used when executing the program.

** syntax
type variablename = vaue;

** example
int myNumber = 100;
char ch = 'A';
String str1 = "abc";

** Types of variables
- Instance Variable - it will be created at Class level and can be used within the class
- Local Variable - it is created at method level and can be used within the method
- Static Vaiable -

* Operators

Operators are used for different operations in java

For more info follow this [[https://docs.oracle.com/javase/tutorial/java/nutsandbolts/opsummary.html][link]].


  





