#+TITLE:Testing (Quality Assurance)
#+AUTHOR: Ravi Kiran
#+DATE: [2021-09-07 Tue]


* Manual Testing
** What is Software?
 Software is a collection of computer programs that helps us to perform a task.
Types of software
System Software - Device drivers, Operating Systems, Servers etc..
Programming Software - Compilers, Debuggers, Interpreters Etc..
Application Software - web Applications, Mobile Apps, Desktop Applications.

** What is Software Testing ?
Software testing is a part of the software development process. Software Testing is an activity to detect and identify the defects in the software. The objective of testing is to release quality product to the client.

** Software Quality Parameters
- Bug-free
- Delivered on time
- Within budget
- Meet requirements and/or expectations
- Maintainable

** What is Project and Product?
If a software application is developed for a specific customer based on the requirement then it is called Project. The companies which are involved in this project are called Project/Service based companies.
Ex: TCS, Wipro etc..

If a software application is developed for multiple customers based on market requirements then it is called Product.  The companies are called Product based companies.
Ex: Google, Microsoft etc..

** What are Error, Bug and Failure?
- Error: An incorrect human action is called an error. Like wrong coding.
- Bug: Deviation from the expected behaviour and actual behaviour is called a Bug/Defect.
- Failure: The deviation identified by the end user is called Failure.

** Why do software have bugs?
- Miscommunication or no communication
- Software complexity
- Programming error
- Changing requirements
- Lack of skilled testers

* SDLC- Software Development Life Cycle

Software Development Life Cycle is a process used by the software industry to Design, Develop and Test Software’s.

The 3 P’s of the Company
- P-People
- P-Process
- P-Product

** SDLC-Phases
- Requirements Analysis- Gathering requirements from the client.
- Design - Design the Blueprint of the software.
- Development - Developing the software or application as per the requirements. 
- Testing - Testing the software or application developed before delivering it to the client.
- Maintenance - The software or application is deployed to the client for usage.

* SDLC Models
** Waterfall Model - 
This is an old and traditional model. Documentation is very important in this model.
- Requirement Analysis - SRS-Software Requirement Specification document
- System Design - Design document
- Implementation - Software
- Testing - Test plan, Test Case 
- Deployment - Installation Manual, 
- Maintenance - 

*** Advantages of  Waterfall Model
- Quality of the product will be good.
- Since requirement changes are not allowed, chances of finding the bugs will be less.
- Initial investment is less since the testers are hired at the later stages.
- Preferred for small projects where requirements are freezed.

*** Disadvantages of  Waterfall Model
- Requirement changes are not allowed.
- If there is a defect in the requirement that will be continued.
- Total investment is more because time taking for rework on defect is time consuming.
- Testing starts only after coding.

** Spiral Model
This type of model is suitable for product based companies.
- Spiral Model
- Spiral Model is an iterative model.
- Spiral Model overcomes drawbacks of the Waterfall model.
- We follow a spiral model whenever there is dependency on the modules.
- In every cycle new software will be released to customers.
- Software will be released in multiple versions. So it is called version control model.

*** Advantage of Spiral Model
- Testing is done in every cycle
- Customers will get to use software in every module.
- Requirement changes are allowed after every cycle before going to the next cycle.

*** Disadvantages of Spiral Model
- Requirement changes is not allowed in between the cycle
- Every cycle of the spiral model looks like a waterfall model.
- There is no testing in the requirement & design phase.

** Prototype Model- Blueprint of the software
Initial requirements from the customer→ Prototype→ Customer→ Design, Coding, testing

** V-Model/ VV-Model
V V means Verification and Validation. In this model testing will be done in every stage.

**** First stage -Requirement Gathering in which the BU(Business Unit) people will gather information from the client and prepare BRS(Business Requirement Specification) / CRS(Customer Requirement Specification) / URS(User Requirement Specification) document.
**** Second stage- Developers or Technical people cannot understand the BRS/CRS/URS document. For this SRS(Software Requirement Specification) document will be prepared. SRS will be prepared by the Product Manager or Project Manager.
**** Third stage- Based on SRS HLD(High Level Design) and LLD(Low Level Design) will be prepared. HLD contains the main modules and LLD contains the Low level or sub modules. It will be prepared by Designers.
**** Fourth stage- Coding will begin in this stage. Once coding is done Unit Testing will be done by the developers. Later the Integration Testing will be done by the developers to test the integrations of the modules. The testing which is done by the developers is called White Box testing. After this the software will be ready and System testing will be by the testers using Black box testing. User Acceptance Testing will be done by the users to test the final software. It is also a Black Box testing Technique

* Types of Testing Techniques

** Static Testing
The testing done by reviewing the documents prepared for the correctness and completeness. This type of testing is called Static Testing.

** Static Testing Techniques
- Review
- Walkthrough
- Inspection

*** Review
Testing will be conducted on documents to ensure correctness and completeness. 
**** Different Types of Reviews
- Requirement Reviews
- Design Reviews
- Code Reviews
- Test Plan Reviews
- Test Cases Reviews

*** Walkthrough
It is an informal view.
- Author reads the documents or code and discuss with peers.
- It's not pre-planned and can be done whenever required.
- Also walkthrough does not have minutes of the meet.

*** Inspection
Inspection will have a proper schedule which will be intimated via email to the concerned developer/tester.
- It’s a most formal review type
- In which at least 3-8 people will sit in the meeting 
- Reader - The author who reads the document
- Writer - The person who records the questions or record the minutes of meeting while reading the documents.
- Moderator - The person who organise the meeting.

** Dynamic Testing
Testing the actual software is called Dynamic Testing.

** Dynamic Testing Techniques
- Unit testing
- Integration Testing
- System Testing
- User Acceptance Testing (UAT)

** Unit Testing
As soon as the coding is completed unit testing is done by developer to check. This testing comes under white box testing.
- A unit is a single component or module of a software
- Unit testing is conducted on a single program or single module.
- Unit testing is white box testing.
- Unit testing is conducted by the developers.

** Unit Testing Techniques
- Basis path testing
- Control Structure testing 
- Conditional coverage
- Loops coverage
- Mutation Testing

** Integration Testing
- Integration testing performed between 2 or more modules.
- Integration testing focuses on checking data communication between multiple modules.
- Integration testing is white box testing technique
- Types of Integration testing
- Incremental integration testing 
- NonIncremental integration testing

** Incremental Integration Testing 
 Incrementally adding the modules and testing the data flow between the modules. Below are the  approaches 
- Top down - Module added should be child of pervious module
- Bottom-up - Module added should be parent of pervious module
- Sandwich/Hybrid Approach - The combination of Top Down and Bottom up approach.

** Non Incremental Integration Testing
All the modules will be tested at once.

** System Testing
Testing Overall functionality of the application with respective client requirements.
It is a black box testing technique
This testing is conducted by testing team
After completion of component and integration level testing we start system testing.
Before conducting system testing we should know the customer requirements.
System Testing Focuses on 
- User interface Testing(GUI)
- Functional Testing
- Non-Functional Testing

** Usability Testing
*** User Acceptance Testing(UAT)
- After completion of system testing the UAT team conducts acceptance testing in two levels.
- Alpha Testing- Testing done in development environment by the end user
- Beta testing - Testing done in a customer environment.
- After completion of these testing the software will go to production where the end user starts using it for real.

** System Testing classified
- GUI Testing
- Usability Testing
- Functional Testing
- Non-Functional Testing

*** GUI Testing: Graphical user Interface testing or GUI testing is a process of testing the user interface of an application. A GUI includes all the elements such as menus, checkboxes, Buttons, Colors, fonts, Sizes, Icons, Content and Images.
*** Usability Testing: Easiness of the application. Checks how easily the end users are able to understand and operate the application.
*** Functional Testing: Functionality is nothing but behaviour of the application. Functional testing talks about how your feature should work. Functional testing involves the following.

- Object Properties testing
- Database Testing
- Error Handling
- Calculations/Manipulations Testing
- Links Existence & Links Execution

** Cookies & Sessions
*** Object Properties Testing: Check the properties of objects present on the application Ex: Enable, Disable, Visible,focus.
Database Testing: DML(Data Manipulation Language) operations by checking the database operations with respect to UI will be tested using small commands like insert, update, delete, select.
Error Handling: Error messages should display verifying the error message while performing incorrect actions on the application. Error messages should be readable, and user able to understand the language/simple language.
Calculations/Manipulation Testing: Test all the calculations in application should work properly with valid data & invalid data.
Links Existence & Links Execution: Only for web apps where exactly the links are placed according to the document is Links Existence. Links are navigating to proper page or not is Links Execution.
Different type of links are there
Internal Links
External Links
Broken Links
Cookies & Sessions: Only for web apps. 
Cookies: Temporary files created by the browser while browsing the pages through the internet.
Sessions: Sessions are created by the server with a limited time slot. If there is no activity for the specified time the session will end and the user needs to login again.

4. Non-Functional Testing : Once the application functionality is stable then we do non-functional testing. It focuses on performance, load it can take and security etc.
Non-Functional Testing includes
Performance Testing
Load Testing
Stress Testing
Volume Testing
Security Testing
Recovery Testing
Compatibility Testing
Forward Compatibility
Backward Compatibility
Hardware Compatibility
Configuration Testing
Installation Testing
Sanitation/Garbage Testing

 
1. Performance Testing
Load Testing : Increase the load on the application slowly and check the speed of the application.
Stress Testing: Suddenly increase or decrease the load on the application and check the speed of the application.
Volume Testing: Check how much data is able to handle by the application.




What is QA QC QE
QA-Quality Assurance
QC- Quality Control
QE- Quality Engineering
QA vs QC

Quality Assurance
Quality Control
QA is process related
QC is the actual testing of the software
High level management comes under QA
People who test the software comes under QC
QA focuses on Building in quality
QC focuses on testing for quality
QA is preventing defects.
QC is detecting defects
QA is Process oriented
QC is Product oriented
QA for entire life cycle
QC for testing part in SDLC


QE - Testing the software using Automation tools. Automation testers are called QE.



